"""Add download tokens and share links

Revision ID: 40f4ec53def4
Revises: b50b9325f431
Create Date: 2026-03-26 19:16:15.139651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f4ec53def4'
down_revision: Union[str, Sequence[str], None] = 'b50b9325f431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_download_tokens_upload_id'), 'download_tokens', ['upload_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_slug'), 'share_links', ['slug'], unique=True)
    op.create_index(op.f('ix_share_links_upload_id'), 'share_links', ['upload_id'], unique=False)
    op.drop_index(op.f('idx_chunks_upload_id'), table_name='chunks')
    op.create_index(op.f('ix_chunks_upload_id'), 'chunks', ['upload_id'], unique=False)
    op.drop_constraint(op.f('chunks_upload_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_upload_id_fkey'), 'chunks', 'uploads', ['upload_id'], ['id'])
    op.drop_index(op.f('ix_chunks_upload_id'), table_name='chunks')
    op.create_index(op.f('idx_chunks_upload_id'), 'chunks', ['upload_id', 'chunk_index'], unique=False)
    op.drop_index(op.f('ix_share_links_upload_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_slug'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_download_tokens_upload_id'), table_name='download_tokens')
    op.drop_table('download_tokens')
    # ### end Alembic commands ###
