"""add_updated_at_drop_api_key_add_chunk_unique

Revision ID: 6e840d7f171d
Revises: 9cea75a042ed
Create Date: 2026-03-27 20:23:12.886090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e840d7f171d'
down_revision: Union[str, Sequence[str], None] = '9cea75a042ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunk_upload_index', 'chunks', ['upload_id', 'chunk_index'])
    op.add_column('uploads', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('uploads', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('api_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('uploads', 'updated_at')
    op.drop_constraint('uq_chunk_upload_index', 'chunks', type_='unique')
    # ### end Alembic commands ###
